# ~/.zshrc: executed by zsh(1) for non-login shells.

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

HISTFILE=~/.zsh_history

# don't put duplicate lines or lines starting with space in the history.
# See zshoptions(1) for more options
setopt HIST_IGNORE_SPACE HIST_IGNORE_DUPS

# append to the history file, don't overwrite it
setopt INC_APPEND_HISTORY SHARE_HISTORY

# for setting history length see HISTSIZE and SAVEHIST in zshoptions(1)
HISTSIZE=10000
SAVEHIST=10000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
# (zsh does this automatically)

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
setopt EXTENDED_GLOB
setopt DOT_GLOB # include dotfiles

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
#force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    PS1='%F{blue}%~%f ❭ '
else
    PS1='%~%f ❭ '
fi
unset color_prompt force_color_prompt

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -- -z)"
    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# colored GCC warnings and errors
#export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'

# some more ls aliases
alias ls='exa'
alias ll='ls -lh'
alias lla='ls -lah'
alias la='ls -a'

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Alias definitions.
# You may want to put all your additions into a separate file like
# ~/.aliases, instead of adding them here directly.

if [ -f ~/.aliases ]; then
    . ~/.aliases
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/zsh.zshrc and /etc/profile
# sources /etc/zsh.zshrc).
autoload -U compinit && compinit

# elixir
installs_dir=$HOME/.elixir-install/installs
export PATH=$installs_dir/otp/28.1/bin:$PATH
export PATH=$installs_dir/elixir/1.19.2-otp-28/bin:$PATH

# custom (dedmonds)
set -o vi
export EDITOR=vim

alias ..="cd .."
alias e="exit"
alias t="tmux"
alias c="clear -x"
alias cls="clear -x"
alias lc="wc -l"
alias scm="racket -e"
alias gimp3="flatpak run org.gimp.GIMP"
alias comp="~/repos/comp/target/release/comp"
alias agora="gemini -i ~/repos/socrates/agora/core/GEMINI.md"
alias roman="figlet -t -f roman"
alias ff="fdfind"
alias bat="batcat"
alias trash="gio trash"
alias enso="~/repos/socrates/support/enso/enso"
alias sposa="~/repos/sposa/.venv/bin/sposa"
alias focus="/home/dedmonds/repos/foc/.venv/bin/python /home/dedmonds/repos/focus/main.py"
alias esposa="nvim ~/base/sonia_database"
alias define="~/repos/code/define/.venv/bin/python ~/repos/code/define/main.py"
alias oc="opencode"
alias ocode="opencode"

# dell xps 13 webcam manual toggle
alias webcam_on="sudo systemctl start ipu6-stream"
alias webcam_off="sudo systemctl stop ipu6-stream"

## sonia app
alias sonia="~/repos/sonia/main/.venv/bin/sonia"
# set up shell completions - register completion script
_sonia_completion() {
    local completions
    completions=$(~/repos/sonia/main/tools/completions.py sonia "$words[CURRENT]")
    compadd -- ${(f)completions}
}
compdef _sonia_completion sonia



# set up fzf key bindings and fuzzy completion
eval "$(fzf --zsh)"

eval "$(zoxide init zsh)"

. "$HOME/.local/bin/env"
. "$HOME/.cargo/env"

function y() {
	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
	yazi "$@" --cwd-file="$tmp"
	IFS= read -r -d '' cwd < "$tmp"
	[ -n "$cwd" ] && [ "$cwd" != "$PWD" ] && builtin cd -- "$cwd"
	rm -f -- "$tmp"
}
