#!/bin/bash

export CLICOLOR=1
export LSCOLORS=ExFxCxDxBxegedabagacad

# aliases
alias grep="grep --color"
alias gcp="git commit -m '...' && git push"

export EDITOR=vi

# history commands
export HISTCONTROL=erasedups # erase duplicates from history
export HISTCONTROL=ignorespace # do not include commands with an initial space in history
